server:
  port: 8081
spring:
  application:
    name: kosinov-keycloak
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  keycloak:
    auth-server-url: http://localhost:8080/auth
    realm: kosinov-keycloak-realm
    resource: kosinov-keycloak-client
    public-client: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: kosinov-keycloak-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/kosinov-keycloak-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/kosinov-keycloak-realm
logging:
  level:
    org:
      springframework:
        security: DEBUG