server:
  port: 8081
spring:
  application:
    name: kosinov-keycloak
  keycloak:
    auth-server-url: http://localhost:8080
    realm: kosinov-keycloak-realm
    resource: kosinov-keycloak-client
    public-client: true
#    username: admin
#    password: admin
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: kosinov-keycloak-client
            client-secret: SEuB33S9GZa1DVlW8mFD9vUhQn1hXBj9
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/kosinov-keycloak-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/kosinov-keycloak-realm
logging:
  level:
    org:
      springframework:
        security: DEBUG